version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/assinatura_email"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
